### ISSUE TITLE
Broken UI - Missing first hour - Watches

### ISSUE THREAD

**Issue by ghost** [forrestguice/NaturalHour#14]
I noticed this only for the date 2022-03-26. 

https://i.postimg.cc/2yB3sWCq/Screenshot-20220326-064224-Natural-Hour.png

**Comment by forrestguice** [comment]
Thanks for the report - I've been able to reproduce it using the screenshot. I think its a time zone / dst bug, occurring on the day of the transition (similar weirdness on 2022-10-29). I probably would have never noticed it (no dst where I live).

**Comment by forrestguice** [comment]
![Screenshot-20220326-064224-Natural-Hour](https://user-images.githubusercontent.com/10246147/160430700-04b6e7ad-ed36-4f1c-ab3d-fb8043b29843.png)

**Comment by ghost** [comment]
Hey. 
Yes it was at the Day of the transition, sorry I totally forgot to mention. I thought the information in the image would be enough (date, time, place). 
Hopefully the stupid dst will be disestablished soon. 

Best regards
