### ISSUE TITLE
watch face show broken daylight

### ISSUE THREAD

**Issue by ghost** [forrestguice/NaturalHour#22]
Using natural hour with Coordinated Universal Time CUT 0 system time zone makes the watch face show broken daylight. How to attach screenshot if needed?

**Comment by svjasonmchristosthefirstsp** [comment]
Screenshot 
![watchface - broken daylight](https://github.com/forrestguice/NaturalHour/assets/138533997/2fa73f30-7eff-4a52-917c-20defdbfca9d)

**Comment by ghost** [comment]
The issue was marked closed do to a slight tap reopening and posting screenshot 
![watchface - broken daylight](https://github.com/forrestguice/NaturalHour/assets/138533997/0955dc86-1691-48fa-bc8c-82d3f417ade9)

**Comment by forrestguice** [comment]
Thanks. 
I'm seeing this too whenever its configured to a timezone that's off by some amount from "local mean time". It appears only the daylight colors are broken, the rest of the clock elements look correct.

**Comment by ghost** [comment]
any progress?
