### ISSUE TITLE
[Bug] - Broken Twilights

### ISSUE THREAD

**Issue by suntimer24** [forrestguice/NaturalHour#30]
**Describe the bug**

Example location: Lattitude: 53,3° N Longitude: 10° E 
Gregorian year count: 2025 

- From 03.04 on, till 23.09, the twilight phases do not have the same duration anymore.

- From 12.05 on, civil and nautical twilights are disappearing and appearing only again on 29.07

Daylight saving time (dst) 2025 in that region is from 30.03. till 26.10.

Notice, that on 21.06 (begin of summer) there's normaly civil twilight and nautical twilight, but no astronomical twilight, but the app shows only astronomical twilight. 

**Screenshots**
![001_-_12 05_-_all_twilight_phases_are_visible](https://github.com/user-attachments/assets/397daf74-e4f9-40ae-8a2c-b316bae4410d)
![002_-_13 05_-_two_twilight_phases_disappearing](https://github.com/user-attachments/assets/b2055e57-3dc0-4b60-9651-eaa490ae7f7b)
![003_-_28 07_-_two_twilight_phases_still_not_visible](https://github.com/user-attachments/assets/2183a7b4-ab1d-433a-9dca-fba390f2010d)
![004_-_29 07_-_all_twilight_phases_appearing_again](https://github.com/user-attachments/assets/61a40ea0-903f-4594-adda-beb942bbe272)

**Version Info:**
 - NaturalHour Version: [0.2.2]
 - Suntimes Version: [0.16.3 (7)]
 - Android Version: [Android 11, LineageOS 18.1]

**Comment by forrestguice** [comment]
Hi. Thanks for taking time to register and report (both here and on the Suntimes tracker). I appreciate it.
I'll work through and comment on these issues as I have the time.

I believe this particular bug is actually fixed in `v0.2.3`, with code currently waiting in https://github.com/forrestguice/NaturalHour/pull/27. I'll try to tag that release soon.

**Comment by forrestguice** [comment]
`v0.2.3` is now available. 🌞

btw, this issue was closed automatically - can you verify that its actually fixed?
